version: '3.7'
services:
  react-docker:
    build:
      context: ./fe.group4
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
  backend:
    build:
      context: ./be.group4
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
